Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,8 +1,13 @@
 name: test
-on: [push, workflow_dispatch]
+
+on:
+  push:
+  workflow_dispatch:
+
 jobs:
   test:
     runs-on: ubuntu-24.04
+
     steps:
       - name: Checkout repo
         uses: actions/checkout@v6
@@ -11,34 +16,38 @@ jobs:
 
       - name: Install iverilog
         shell: bash
-        run: sudo apt-get update && sudo apt-get install -y iverilog
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y iverilog
 
-      # Set Python up and install cocotb
-      - name: Setup python
+      - name: Setup Python
         uses: actions/setup-python@v6
         with:
           python-version: '3.11'
 
       - name: Install Python packages
         shell: bash
-        run: pip install -r test/requirements.txt
+        run: |
+          pip install -r test/requirements.txt
 
       - name: Run tests
+        working-directory: test
         run: |
-          cd test
           make clean
           make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
+          if grep -q failure results.xml; then
+            echo "Cocotb tests failed"
+            exit 1
+          fi
 
       - name: Test Summary
+        if: always()
         uses: test-summary/action@v2.4
         with:
           paths: "test/results.xml"
-        if: always()
 
-      - name: upload waveform and test results
-        if: success() || failure()
+      - name: Upload waveform and test results
+        if: always()
         uses: actions/upload-artifact@v7
         with:
           name: test-results
